version: "3.9"

services:
  postgres:
    image: "postgres:13.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
      POSTGRES_DB: "weno"
