version: "3.9"


volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
      POSTGRES_DB: "wenop"
