version: "3.3"

services:

  postgres:
    image: "postgres:13.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
      POSTGRES_DB: "vinplan"

  redis:
    image: "redis:6.0-alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"

